api:
  binance_base_url: https://api.binance.com
  binance_testnet_url: https://testnet.binance.vision
  rate_limit: 600
  retry_attempts: 3
  timeout: 30
asset_classes:
  active: crypto
  crypto:
    base_currency: USDT
    exchange: binance
    symbols:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    - ADAUSDT
    - DOTUSDT
    - LINKUSDT
    timeframe: 1h
    trading_hours: 24/7
  stocks:
    base_currency: USD
    exchange: alpha_vantage
    symbols:
    - AAPL
    - GOOGL
    - MSFT
    - TSLA
    - NVDA
    - META
    timeframe: 1h
    trading_hours: 9:30-16:00 EST
data_sources:
  backup: alpha_vantage
  enable_fundamental_data: false
  enable_sentiment_data: false
  enable_websocket: true
  historical_days: 180
  primary: binance
  update_interval: 300
database:
  echo: false
  name: trading_bot.db
  type: sqlite
feature_flags:
  enable_dark_pool_analysis: false
  enable_macro_indicators: false
  enable_news_analysis: false
  enable_options_flow: false
  enable_sentiment_analysis: false
  enable_social_media_analysis: false
  enable_technical_indicators: true
  enable_volume_profile: false
logging:
  backup_count: 3
  enable_console: true
  enable_file: true
  file: logs/trading_bot.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 5MB
models:
  base_models:
  - xgboost
  - lightgbm
  compressed_serialization: true
  cross_validation_folds: 3
  feature_engineering: true
  hyperparameter_optimization: false
  lazy_loading: true
  lookback_window: 50
  meta_models:
  - ridge
  parallel_loading: true
  prediction_horizon: 4
  retrain_frequency: 24
  type: xgboost
  use_cache: true
monitoring:
  alert_thresholds:
    max_drawdown: 0.08
    max_var: 0.03
    min_sharpe_ratio: 1.2
  enable_alerts: true
  enable_dashboard: false
  enable_metrics: true
  health_check_interval: 60
  metrics_port: 8000
performance:
  batch_size: 16
  cache_ttl: 600
  enable_gpu: false
  enable_parallel_processing: true
  max_memory_usage: 0.6
  num_workers: 2
risk_model:
  confidence_level: 0.95
  enable_scenario_analysis: false
  enable_stress_testing: false
  max_portfolio_var: 0.03
  time_horizon: 1
  type: var
security:
  encrypt_api_keys: true
  max_login_attempts: 3
  session_timeout: 3600
strategies:
- enabled: true
  lookback_period: 20
  max_position_size: 0.05
  min_confidence: 0.8
  min_signal_strength: 0.7
  name: mean_reversion
  rsi_overbought: 70
  rsi_oversold: 30
  stop_loss: 0.02
  symbols:
  - BTCUSDT
  - ETHUSDT
  take_profit: 0.04
  timeframe: 1h
  type: mean_reversion
  zscore_threshold: 2.0
trading:
  base_currency: USDT
  initial_balance: 10000
  max_daily_trades: 10
  max_drawdown: 0.1
  max_position_size: 0.05
  mode: paper
  risk_free_rate: 0.02
  stop_loss: 0.02
  take_profit: 0.04
